# Generated by Django 1.11.21 on 2019-07-15 14:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_zoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticredential',
            name='launch_url',
            field=models.URLField(blank=True, default='https://applications.zoom.us/lti/rich', max_length=1024),
        ),
    ]
