# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-08 13:26


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edx_zoom', '0002_lticredential_launch_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('location', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('managed', models.BooleanField(db_index=True, default=False)),
                ('first_access', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_access', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='launchlog',
            unique_together=set([('user', 'location')]),
        ),
    ]
